#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : krest
Version  : 1.3.2
Release  : 6
URL      : https://files.pythonhosted.org/packages/e6/c6/a798db248d292e1ec7e23d9a34ad8b3329dfea264a3d62851343df919bdb/krest-1.3.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/e6/c6/a798db248d292e1ec7e23d9a34ad8b3329dfea264a3d62851343df919bdb/krest-1.3.2.tar.gz
Summary  : The Kaminario REST (krest) is a client library that provides ORM like interface for working with Kaminario K2 REST API
Group    : Development/Tools
License  : Apache-2.0
Requires: krest-python = %{version}-%{release}
Requires: krest-python3 = %{version}-%{release}
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : requests

%description
Please see the project homepage_ for full description.

%package python
Summary: python components for the krest package.
Group: Default
Requires: krest-python3 = %{version}-%{release}

%description python
python components for the krest package.


%package python3
Summary: python3 components for the krest package.
Group: Default
Requires: python3-core
Provides: pypi(krest)
Requires: pypi(requests)

%description python3
python3 components for the krest package.


%prep
%setup -q -n krest-1.3.2
cd %{_builddir}/krest-1.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600788827
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
